title: "Widen Engineering"
description: "The blog of the Widen Engineering Team."
timezone: "America/Chicago"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://engineering.widen.com"
email: "engineering@widen.com"

remote_theme: widen/jekyll-theme-guardian@v1.0.1
guardian:
  style:
    logo_url: https://embed.widencdn.net/img/widen/c17yrvuaac/400px@2x/Widen Engineering White Logo.png?u=mcuc7i
    header_background_url: https://embed.widencdn.net/img/widen/m4ml1kuspv/exact/1680x90_Engineering Blog Banner.png?keep=c&crop=yes&u=ksmgip
  social_links:
    twitter: widendev
    github_org: widen
    github_repo: widen.github.io
    email_subscription_url: https://feedburner.google.com/fb/a/mailverify?uri=WidenEngineering
  tracking:
    google_analytics_code: UA-1206716-19
    disqus_shortname: widen-engineering


# DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

permalink: "/blog/:title/"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  smart: true
  input: GFM
  syntax_highlighter: rouge
exclude: [Makefile, Rakefile, Gemfile, Gemfile.lock, README.md, vendor]
repository: widen/widen.github.io
plugins: ['jekyll-github-metadata', 'jekyll-sitemap']
